### ISSUE TITLE
Disable JCache serialization

### ISSUE THREAD

**Issue by ben-manes** [aalmiray/caching-benchmarks#1]
By default JCache requires that the key & value be serialized when entries flow in and out of the cache. An anonymous cache is forced into this configuration at `JCacheRegionFactory#newDefaultConfig()`. This adds a high tax on Caffeine, due to using custom providers for the other implementations. Since Infinispan 9 adopted Caffeine and is faster, we know that the slow down has to be in the JCache layer.

Try adding the following to `hibernate-caffeine/src/test/resources/application.conf`.

```
caffeine.jcache {
  org.hibernate.cache.spi.UpdateTimestampsCache {}
  org.hibernate.cache.internal.StandardQueryCache {}
  org.kordamp.javatrove.cache.HbmAddress {}
  org.kordamp.javatrove.cache.HbmPerson {}
}
```

This now adds named caches with Caffeine's [defaults](https://github.com/ben-manes/caffeine/blob/master/jcache/src/main/resources/reference.conf), where `store-by-value` is `false`.

When running the tests we see 
```xml
<!-- Before -->
<event key="em1 [load L1C1; load L2C]" ns="228064678" ms="228.064678"/>
<!-- After -->
<event key="em1 [load L1C1; load L2C]" ns="58831113" ms="58.831113"/>
```

When comparing, we should see that all implementations have similar performance after the initialization cost is paid off. This is because the caches are unbounded and there is no concurrency, so the work involved a map lookup and code path overhead. Without digging deeper and a using a proper JMH harness to remove JIT warmup, its hard to eyeball where the remaining differences are from.

**Comment by ben-manes** [comment]
I bumped up the iteration count to 50 and the noise between providers goes away, so it was mostly just warmup as expected. 

```
=== Caffeine: Iteration 49 ===
em1 [load L1C1; load L2C] time:  22.381215 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit L2C; load L1C2]  time:  18.360090 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit l1C2]            time:   3.220275 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit L2C; load L1C2]  time:  15.673522 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [load L1C2; load L2C] time:  16.581939 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit l1C2]            time:   4.018830 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em3 [hit L2C; load L1C3]  time:  16.227840 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em3 [hit l1C3]            time:   2.679217 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]

=== Infinispan: Iteration 49 ===
em1 [load L1C1; load L2C] time:  32.678885 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit L2C; load L1C2]  time:  33.880992 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit l1C2]            time:   5.167954 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit L2C; load L1C2]  time:  22.346797 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [load L1C2; load L2C] time:  18.071286 ms;  BEFORE [L1C:  true, L2C: false] AFTER  [L1C:  true, L2C: false]
em2 [hit l1C2]            time:   4.710231 ms;  BEFORE [L1C:  true, L2C: false] AFTER  [L1C:  true, L2C: false]
em3 [hit L2C; load L1C3]  time:  24.230545 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em3 [hit l1C3]            time:   3.261306 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]

=== Hazelcast: Iteration 49 ===
em1 [load L1C1; load L2C] time:  29.791293 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit L2C; load L1C2]  time:  27.140037 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit l1C2]            time:   5.966800 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit L2C; load L1C2]  time:  20.237263 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [load L1C2; load L2C] time:  17.558369 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit l1C2]            time:   3.539219 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em3 [hit L2C; load L1C3]  time:  18.751561 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em3 [hit l1C3]            time:   3.737313 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]

=== Ehcache: Iteration 49 ===
em1 [load L1C1; load L2C] time:  28.394867 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit L2C; load L1C2]  time:  21.885681 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit l1C2]            time:   3.840493 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit L2C; load L1C2]  time:  20.697507 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [load L1C2; load L2C] time:  42.547986 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit l1C2]            time:   4.604301 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em3 [hit L2C; load L1C3]  time:  24.394398 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em3 [hit l1C3]            time:   4.947253 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]

=== EclipseLink: Iteration 49 ===
em1 [load L1C1; load L2C] time:  15.960035 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit L2C; load L1C2]  time:  11.835363 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit l1C2]            time:   9.246745 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit L2C; load L1C2]  time:  11.527148 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [load L1C2; load L2C] time:  11.952289 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em2 [hit l1C2]            time:   9.181924 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em3 [hit L2C; load L1C3]  time:  11.425138 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
em3 [hit l1C3]            time:  10.730407 ms;  BEFORE [L1C:  true, L2C:  true] AFTER  [L1C:  true, L2C:  true]
```

**Comment by aalmiray** [comment]
Added also more hits to L2C and the numbers look promising

                                Eclipselink Infinispan  Hazelcast   Ehcache     Caffeine
    em1 [load L1C1; load L2C    17.102244   22.87885    17.215866   32.974687   20.61203
    em2 [hit L2C; load L1C2]    10.355298   19.504793   19.196122   15.675954   14.829227
    em2 [hit l1C2]               8.613029    2.361707    2.151642    2.83681     2.381
    em2 [hit L2C; load L1C2]    10.291512   23.59982    14.063084   15.522052   15.325738
    em2 [load L1C2; load L2C    11.630086   13.703671   13.605992   20.679246   14.630494
    em2 [hit l1C2]               8.979271    2.254764    2.19284     2.849621    2.246998
    em3 [hit L2C; load L1C3]    10.807325   19.209807   17.47611    15.778694   15.74986
    em3 [hit l1C3]               8.096646    2.282186    2.28769     2.239157    2.450497
    em4 [hit L2C; load L1C4]    10.843495   25.10257    14.864844   16.069229   20.97275
    em4 [hit l1C4]              10.337606    2.2177      2.200093    2.24532     2.320835
    em5 [hit L2C; load L1C5]    10.731039   18.511177   16.926909   15.706729   14.554578
    em5 [hit l1C5]               7.932429    3.14165     2.645379    2.358961    3.017609
    em6 [hit L2C; load L1C6]    10.77517    18.749057   14.620632   15.755792   15.337391
    em6 [hit l1C6]               9.38149     2.196833    2.178647    2.262769    2.26086
    em7 [hit L2C; load L1C7]    11.414244   18.679805   20.425494   16.048997   15.10204
    em7 [hit l1C7]               9.66061     2.372273    2.402846    2.275243    2.380356
    em8 [hit L2C; load L1C8]    10.827184   18.136701   14.084691   15.493943   14.758064
    em8 [hit l1C8]               8.835726    2.196845    2.485593    2.340247    2.283307
    em9 [hit L2C; load L1C9]    11.642551   18.427292   14.237058   16.021266   14.803051
    em9 [hit l1C9]               8.588085    2.197703    2.370404    2.372082    3.114202

@ben-manes: may I suggest to add more content to Caffeine's wiki page on JCache about this particular setting? I couldn't find it anywhere and I may not be the only one.

Also, I'd love to use JMH but it's likely I'll get a frowny face from Alexey as you're "not supposed" to use JMH for such a big piece of code, M stands for micro after all 😉

**Comment by ben-manes** [comment]
It does warn for annotation support, but I didn't know that Hibernate did the same. It's just an awful spec with a lot of hidden gotchas...

>Be weary of anonymous caches, which are created using the specification's defaults settings. This means a cache that never expires and stores by value (serialization).

**Comment by ben-manes** [comment]
Please add `org.kordamp.javatrove.cache.HbmPerson.addresses {}` to avoid serialization of the new cache. The core issue is JCache and that Hibernate doesn't log any warnings that it defaults to bad behavior.

**Comment by ben-manes** [comment]
It seems that even the Ehcache conceded that their promotion of silently creating bad caches was flawed. In their samples they now reject anonymous caches. Filed an [issue](https://hibernate.atlassian.net/browse/HHH-11953) against Hibernate.

**Comment by aalmiray** [comment]
Fixed. Would it be possible for Caffeine's JCache integration to configure named caches by default? The other caching solutions perform this task already thus the information is known.

Also, these benchmarks are currently run with default settings to test out stock configuration. I'm planning in adding a different set of benchmarks with vendor specific configuration that would make them perform better. Is there anything else that I should know about Caffeine in order to make it perform better?

On one scenario there will be 12k entities and 4k collections; on the other is 30k entities and 10k collections. These numbers are for testing cache boundaries and may need to be adjusted.

**Comment by ben-manes** [comment]
Unfortunately doing so would violate JSR-107 which validates the behavior in its TCK. The better solution would be to replace Hibernate's JCacheRegionFactory with vendor defaults. The other providers wrote integrations prior to JCache, but Ehcache 3 will suffer the same problem as they wrote the JCache adapter for their support.

Hibernate doesn't want to maintain integrations and I don't use the ORM, so JCache seems the best alternative. It's frustrating but available.

Caffeine is highly concurrent and has a great hit ratio. It's targeting moderate to large caches (most likely to exhibit frequency) where latency matters under load. It excels in these stress cases that the others fail badly at (see my benchmarks). But if you have low concurrency and no eviction, all should perform adequately and you may not be able to differentiate them.

Thanks for making the fixes. 😀

**Comment by aalmiray** [comment]
Got it. The next version of the benchmarks not only deal with higher data rates but also with concurrent access. There will be additional benchmarks with various percentages of writes.

**Comment by ben-manes** [comment]
I finally got around to figuring out why Ehcache’s performance is so awful when it has to evict data. You might enjoy the [analysis](https://gist.github.com/ben-manes/6312727adfa2235cb7c5e25cae523ad0#file-ehcache-md). While the devs refuse to fix it, hopefully most users are fine because Spring Cache added the suggested mitigation. I don’t know if ehcache is used much anymore, but I see it in generated blog spam.
